name: air_quality_app
description: "A high-impact air quality monitoring application for the ISRO hackathon."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  
  # Caching & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Networking & APIs
  http: ^0.13.6
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  
  # Location Services
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # UI & Visualization
  google_maps_flutter: ^2.6.1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  lottie: ^3.0.0
  
  # Firebase for Push Notifications

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  google_api_headers: ^1.6.0 # Downgrading to a compatible version
  google_places_autocomplete_text_field: ^1.0.0 # Replacing flutter_google_places
  google_maps_webservice: ^0.0.20-nullsafety.5 # Ensuring compatibility
  # flutter_google_places: ^0.3.0 # This will be removed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Add assets to your application
  assets:
    - .env

 